# Libraries ---------------------------------------------------------------
install.packages(c("remotes", "tidyverse", "psych", "plotly", "rmarkdown", "skimr"))
if (!requireNamespace('BiocManager', quietly = TRUE))
  install.packages('BiocManager')
BiocManager::install('PCAtools')
install.packages("httr")
install.packages("ggplot2")

# Packages ----------------------------------------------------------------
library(ggplot2)
library(remotes)
library(tidyverse)
library(psych)
library(plotly)
library(rmarkdown)
library(skimr)
library(BiocManager)
library(httr)
library(dplyr)
library(data.table)
