# Libraries ---------------------------------------------------------------
# install.packages(c("remotes", "tidyverse", "psych", "plotly", "rmarkdown", "skimr"))
# if (!requireNamespace('BiocManager', quietly = TRUE))
#      install.packages('BiocManager')
# BiocManager::install('PCAtools')
# install.packages("httr")
# install.packages("ggplot2")
# install.packages("corrplot")
# install.packages("ggcorrplot")
# install.packages("MASS")
# install.packages("GGally")
# install.packages("readr")
# install.packages("nnet")
# install.packages("factoextra")
# install.packages("DescTools")
# install.packages("patchwork")
# install.packages("gridExtra")
# install.packages("ggmosaic")
# install.packages("treemapify")
# install.packages("vcd")

# Packages ---------------------------------------------------------------- 

library(ggplot2)
library(remotes)
library(tidyverse)
library(psych)
library(plotly)
library(rmarkdown)
library(skimr)
library(BiocManager)
library(httr)
library(dplyr)
library(data.table)
library(corrplot)
library(ggcorrplot)
library(MASS)
library(readr)
library(stringr)
library(nnet)
library(stats)
library(factoextra)
library(cowplot)
library(DescTools)
library(patchwork)
library(gridExtra)
library(ggmosaic)
library(treemapify)
library(vcd)

